version: "3"
services:
  jonkofee-music_postgresql:
      container_name: jonkofee-music_postgresql
      build: postgresql
      restart: always
      environment:
          POSTGRES_PASSWORD: devpass
          POSTGRES_USER: jonkofee-music
      ports:
        - "6543:5432"
  jonkofee-music_api:
    container_name: jonkofee-music_api
    build: apache+php
    ports:
      - "420:80"
      - "8000:8000"
    volumes:
        - "../:/app"
    working_dir: /app
    tty: true
    links:
      - jonkofee-music_postgresql
    depends_on:
      - jonkofee-music_postgresql